### ISSUE TITLE
Can not run tests selectively with `pytest`

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1033]
It seems like it is not possible to run tests selectively with `pytest`, for example with `pytest -k test_beamline` or `pytest test/test_beamline_routes.py`. 

As far as I can tell, the issue is that both mxcube and pytest itself "fight" for access to `sys.argv` (via `argparse`).

**Comment by fabcor-maxiv** [comment]
I have some refactoring in mind that could help solve this. I can work on it, especially since I want to work on tests for authentication (in particular for #1032).

**Comment by marcus-oscarsson** [comment]
I never really run just one test myself, but that is of course convenient, so I did not see this issue myself.  Sounds excellent that you will have a look, I think it will be of good use :). Are you sure its not the fixtures that are causing this issue rather than `argparse` ?. I'm not certain that `sys.argv` is used when we call the mxcube server from `pytest` ?

**Comment by fabcor-maxiv** [comment]
Should be easy to reproduce the issue, for example with `pytest -k test_get_beam_info`.

For now I am convinced, that the issue is with `sys.argv`. I have a potential fix ready. It uses [this approach](https://jugmac00.github.io/blog/testing-argparse-applications-the-better-way/). I will create pull request in a minute (if all goes well).

**Comment by fabcor-maxiv** [comment]
Should be fixed with https://github.com/mxcube/mxcubeweb/pull/1034
