### ISSUE TITLE
Store session data

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#115]
Save relevant session data into a database (redis?), with some kind of expiry date. 
We need to store two queues: sample_changer and manual mounting queues
Related to #113 and #58

**Comment by mguijarr** [comment]
Can we close this one too? Or be more specific in features we want to include in this issue

**Comment by meguiraun** [comment]
mmmm... we can store all the queue in the session/redis db, and every time a change in the queue is done, it is also updated. But, we would need to fix the way we retrieve this data, so, I agree we can close this but open an additional issue ~"retrieve stored session".

However, I would suggest to make a workaround for the retrieving (for example... ignore saved session) so we do not have those annoying existing queues laying around, and of course, fix it later. I have the feeling we are spending a lot of time in the queue (and related stuff like session) and very little in the actual work that will be needed first: sample view, etc.

Would you accept something like an easy workaround and retake the session issues later?

**Comment by mguijarr** [comment]
I think we should be more specific and more fine-grained in our issues, so I am in favor of closing
this one and creating new ones for the session and queue problems.

It would help having a better view of what is left to be done ; we (Marcus and I) would be happy to work on the queue and session too, but for the moment it is a bit fuzzy what is working and what is
not. If you have a list of bugs you already identified, please share it with us :)

It is very important to have the session mechanism working fine. We never had an equivalent session
feature in past MXCuBE versions, it may explain our difficulties.

What would be the easy workaround ?
My advice to you is to disable the session in your private repositories if it helps, but I won't accept a
PR disabling it because I consider tests have to be done with session enabled. Otherwise we will do
a lot, and suddenly we will realize we miss the session and it would be even more difficult to add
it later.

Don't hesitate to correct me if you feel I am wrong.

**Comment by meguiraun** [comment]
I will open a few issues for those bugs and we can distribute among us.

For the session, earlier we were storing (and retrieving) the state coming from the client, we changed that so the state of the queue is always whatever the server has. So now, if the client asks for the state it will not receive a simple react state that can easily apply. The major problem is that this is a ~big refactoring. That's why I say about the workaround.

Anyway, let's close this one and I will open new ones and we move the discussion there.

**Comment by mguijarr** [comment]
Thanks Mikel :+1:
