### ISSUE TITLE
Characterisation result

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#117]
Retrieve and show the result of the characterisation, and apply proposed strategy to the collection

**Comment by amilan** [comment]
Let's add some more info to the issue.

**Task definition**
As a user, I want to see characterization results from EDNA in a modal, so that will make me easier to find my results.

**Acceptance Criteria**
Given some characterization results, when I click on "see results" a modal is opened showing that information.

**Comment by mguijarr** [comment]
I would add in the Acceptance Criteria that results have to be available from the Sample Grid too.

**Comment by amilan** [comment]
Thanks for the suggestion.
