### ISSUE TITLE
Web interface design

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#12]
* Component skeleton, for using as a basic building block but also for making easy future enhancements or additions from non developers
* Define a naming convention for the elements of the interface?
* Define the experiment layout:
  * Blocks/components treated as current bricks
  * Some actions generated in a component may cause new actions in other components as well as in the server/equipment/etc.
* Web technology to be used:
  * React: to populate the page as new elements are required
  * Javascript to handle:
      - Actions on user interactions
      - Receive events and messages from the server and update the corresponding element on the interface (a data field, experiment finished, etc.)

The main idea is of the new layout is to simplify the sample tree design:
* Connect to ispyb and show only the samples available in the sample changer (can de done automatically or triggered by the user)
* Some kind of filtering is needed due to the high number of samples that could be available for the experiment, by name, protein, etc.
* Synchronization capabilities between Ispyb and the sample changer

The interface layout is split into different views (web pages), therefore decoupling the sample lists and experiment configuration (in a kind of batch mode) from the sample centring. The latter shows an experiment tree but only for a single sample, basically the one that is mounted. The transition between the pages/views must display a status message for the user (e.g “Mounting sample” message with a progress bar). More pages will be needed such as one for the optimisation, for the energy scan, etc.

There have been defined the first views that are required in the beginning, which are considered as a first approach and prone to change in the future:
* The sample centring page: issue https://github.com/mxcube/mxcube3/issues/9
* The sample list view: additional issue needs to be created

![web-layout](https://cloud.githubusercontent.com/assets/12758327/10162222/2c23228c-66aa-11e5-8ecd-f4eecfbd7b27.JPG)

**Comment by meguiraun** [comment]
For now, closed as an initial design has been proposed and discussed, and accepted.
* leave the resize of the image
* current setup
  * expert like button, otherwise read only fields
  * confirmation dialog
  * possibility to move above the image
* experimental setup
  *if the user also changes E -> confirmation dialog

![image](https://cloud.githubusercontent.com/assets/12758327/11401268/01e6b2f8-9392-11e5-98ac-15e0bf9390ca.png)

![image](https://cloud.githubusercontent.com/assets/12758327/11401307/4d7c7572-9392-11e5-923d-eefdeb8397a9.png)

**Comment by mguijarr** [comment]
Following our meeting at ALBA, here are 2 sketches of the UI with the modifications we agreed on:

* the login area has been moved to a Login page (not shown), Login is the main page when user lands on MXCuBE 3 application
* after user logs in, the main screen looks like this:
    ![mxcube3_layout](https://cloud.githubusercontent.com/assets/2834952/11587230/3fa52ff6-9a78-11e5-81cd-18a88a704b42.png)
    * the samples from the Sample Changer are shown in a **grid**, each sample is a **card** displaying various information (sample location, data matrix). When clicking `Synchronize ISPyB`, samples are matched with ISPyB information, and then more data can appear like protein name for example
    * a `Filter` input can be used to apply filtering on the samples displayed in the grid
    * the grid has limited space, with **vertical scrollbar** if needed
    * samples in the grid can be selected
    * when clicking `Add` button, samples are added to the **Samples list**
    * **Samples list** can be re-ordered with up/down arrows buttons
    * **Samples list** allow selection of samples, some **data collection protocols** can be attached to sample(s), like **Characterization** or **Auto** (**Auto** means fully automatic workflow, the workflow in itself is selected via a dropdown list)
    * Once a sample is mounted by clicking on the little icon next to sample in the list, view will switch to **Data Collection** / the same can be achieved by clicking `Run >` button, in this case the first sample in list is mounted

**Comment by meguiraun** [comment]
Deadline arrived, it is fine for me as you explained.
Thanks for writing all of this... and the hand-drawing sketches are perfect!

**Comment by mguijarr** [comment]
Ok so let's close this and move on.

**Comment by JieNanMAXIV** [comment]
Following our meeting at MAXIV, below are the the Sample UI and DataCollection UI that we agreed on:

**Overview**
Sample Mount mode (combobox): 

- 	Manual, Data collection view but without “To do list” (Queue to run)  
- 	SC (by default, used most), Sample View (with Sample cards)
- 	Plate, to be decided later
The most common mounting method is to use SC and there are three kinds of experimental approaches: 
- 	Manual, user only selects a list of samples for exp.
- 	Semi-automatic (used most) , select a list of samples and add data collection methods / pipeline, collect data INTERACTIVELY (meaning users may need to add/change methods, change parameters)
- 	Fully automatic, unattended data collection, select a list of samples and add pipelines (or retrieved from ISPyB)

For the moment, if the diffraction plans are retrieved from ISPyB and modified, the changes will not be synchronized back to ISPyB.  

**Sample Page (Default home page after login)**
![20160225_sampleview](https://cloud.githubusercontent.com/assets/14329743/13424921/e6133548-dfa3-11e5-902f-ddd6f233d112.png)
-	Display samples that are detected in the SC
-	Sample cards, containing info of sample name, SC pos, tasks and their status, results linking to ISPyB, 
-	Sample mount mode, manual /SC /Plate
-	Sync ISPyB (Button), sample info is updated (only one direction, synchronized from ISPyB)
-	Filter/search (to only show a few samples), free text search 
-	A sample card has four status, 
  1. No operation
  2. Selected (by single click) 
  3. Added in the queue (with a queue icon in the corner?)
  4. Selected and added in the queue
-	On the right side (or top) of the sample cards, two groups of buttons
 1) a group for cards management
  1. Add to Queue
  2. Select all
  3. Unselect all

 2) In the middle, another group of checkbox/buttons for experiments , including Element analysis, Characterization, Data Collection, pipeline (combobox), disabled if no samples are selected. 
When clicking any of the above button, a modal box will pop up with experimental parameters. The modal box also contains a checkbox “X-ray Centring” (unticked by default) and a checkbox “only use lucid” (unticked by default), where data collection are carried on the lucid centring pos.  ”Close” and ”Add xx” buttons in the bottom. After pressing “Add xxx”, tasks will be added to the sample cards. If the samples are not in the “queue to run” list, it will be added to the queue. 

**Queue**
On the very top, collected /total, display the numbers of collected samples and the total numbers in the queue including history, estimated time left (wish).
The queue includes three parts:

1.Currently mounted sample

- 	Sample has unmount, run, stop, pause button. If clicking “run”, only selected tasks in the current sample will be executed. 
- 	Tasks with checkbox, labels (shape item name), icon for experimental info (parameters), results (link to ISPyB) for executed tasks and delete for unexecuted ones. 
- 	Tasks can be reordered by drag-drop, but only applied to unexecuted ones. Diffraction plan is grouped together with the corresponding characterization (), and drag-drop will apply to the group.
- 	Taskgroup will be transparent to users (but kept in HO for now), DC plan with multiple sweeps is presented as one entry, the same way as interleave in Qt4 version.

2.Queue to run

- 	Collapsed by default
- 	“Clear” button to remove all samples from the list, their tasks will be removed from the samples as well (in the sample card), except for those retrieved from ISPyB.
- 	Only display sample name & position in SC (no checkbox in front of each sample)
- 	With delete (to remove from the list) and mount button
- 	Samples can be reordered by drag-drop
- 	Move hover a sample, the sample card info will be displayed. 

3.History 

- 	Collapsed by default
- 	In chronological order, unchangeable
- 	Sample only has mount button for remount
- 	Tasks with status color code and links to the results in ISPyB.
- 	Task parameters cannot be visualized (note: when the sample is remounted, the parameters of the history tasks will be available). 
- 	When a sample from history is remounted, its previous history should appear both in the current and history. After this sample is finished and unmounted, the latest history should be merged with the previous history and displayed at the top of the history. Note, history is merged only if the sample name (prefix) and sample position matches (this is to avoid the case that user remounts a sample in the history, which has been moved out from the SC and a new puck is added). 
- 	Samples, that are only mounted w/o collection, should also go to history

The three parts should contain a scroll bar individually, so that even with a long list of “to run” and “hisotry”, users can still read other parts easily.

At the bottom of the queue, buttons for the operation of the whole queue, stop, run, pause 

**Data Collection Page**
![20160225_datacollection](https://cloud.githubusercontent.com/assets/14329743/13426943/21e838f4-dfb1-11e5-9ffc-d3b1ce671a6a.png)

Two modes:
- SC mode, with the queue as described above. When users click “DataCollection” menu bar, or mount any samples in the queue, or run the queue, “Data Collection” Page will be displayed. 
- Manual mode

Components / Modules:
-	Queue, the same as the one in Sample View
-	Sample video
-	Sample motors
 1. Rotation motors, omega, kappa, phi, (user can change the absolute values and also move them in defined steps )
 2. Translation motors, X, Y, Z (same as above, but perhaps in readable mode by default!?)
-	Beamline info, by default the info is only readable/text. If users need to change the values, one can click the checkbox to activate the editable mode. 
 1. Detector distance /resolution
 2. Beam related information, including beam size, energy/wavelength, beam intensity, photon flux(only readable), transmission
-	Sample status bar, to display the sample’s status e.x. mounting, mounted, lucid2, collecting… 
-	Snapshot, save, zoom, front/back light, lucid, zoom, tools (for measurement), “Add line”, “add grid”, “list” buttons or icons, list button is to display Shape items and their related operations, including hide, select, move to the beam center. Note: for Grid, the rotation motors’ values are needed (therefore need to be saved).
-	A checkbox to disable video during data collection (for remote access in case of slow network)
The positions of the above components need to be optimized, and perhaps should be customizable by users.  

Selection of Points/lines/grids:

- Ctrl+Click for multiple selection 
- Can be also done by drawing a rectangle box to select all items within the area. If it’s a mix of different shape items, following the priority of Grid > line > point. In the case that users want to select shape items with low priority, they need to hide or delete items with high priority. 

Add collection tasks via Sample View:
Select 1-n shape items -->right click --> a list of tasks that are related to the shape items will be displayed. After single click of a task, a Modal will pop up for the input of experimental parameters. For the Modal:

- Only display the most common ones, for advanced settings, one can click the arrow to display all parameters.
- In the bottom of the Modal, a few buttons “add to queue”, “Run now”
- Note, in the parameter list, add beamsize

_Data Collection Page in Manual mode_

-	In the sample view, if user selects “manual” mode to mount sample, it will be redirected to the “data collection” Page in manual mode
-	The “Queue” only contains “current” and “history” sections. 
-	Current doesn’t have mount button, but instead a “New sample” Button. When it’s clicked, the parameters of prefix, sample name, path will be reset to default, points/lines/grids will be cleared, all “Tasks” in the “current” will be grouped under the previous sample and added to the top of the history.
