### ISSUE TITLE
Rename directory `/test` to `/demo`

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#1350]
Rename directory `test` (https://github.com/mxcube/mxcubeweb/tree/develop/test) to `demo`.

**Comment by fabcor-maxiv** [comment]
Related to this? https://github.com/mxcube/mxcubecore/issues/944

**Comment by marcus-oscarsson** [comment]
Yes a subset :)

**Comment by fabcor-maxiv** [comment]
If we rename `/test` to `/demo`, then *pytest* will not be able to find the tests anymore (not by default, not without telling pytest explicitly where the test files are).

Or am I missing something? I have not spent much time thinking about this.

**Comment by elmjag** [comment]
IMHO the `https://github.com/mxcube/mxcubeweb/tree/develop/test/HardwareObjectsMockup.xml` should be moved up out from `test` and be renamed to `demo`.

The rest of the `test` folder should remain as-is. There _are_ actual tests there as well.

Another detail, the tests _probably_ needs to be updated, I think they reply on files in `HardwareObjectsMockup.xml`.

**Comment by marcus-oscarsson** [comment]
Yes, then I guess we have to discuss exactly how we want to configure the tests.  We still need a set of configuration files that configure the test hardware objects. So, `https://github.com/mxcube/mxcubeweb/tree/develop/test/HardwareObjectsMockup.xml` should perhaps be copied to a folder called `demo` or even `demo-configuration` (one level up as you mentioned @elmjag). 

How do you think we should configure the tests, should we have one folder with all configuration files that we can override for specific tests, should each test have their set of configuration files (quite tedious IMO) or some other solution ?

**Comment by elmjag** [comment]
I think we can start with changing tests to use the new `demo` folder. Not sure if it's possible, but I think it would be good that there are at least some tests that exercise the `demo` folder.

Future test may use their own config files, if they need to test some configuration not covered by `demo`. They should go inside the `test` folder.

I can take a look at this. I have an itch since long time to rename the `HardwareObjectsMockup.xm` folder :)

**Comment by marcus-oscarsson** [comment]
Ok

**Comment by elmjag** [comment]
I started look into this, but got blocked by this: https://github.com/mxcube/mxcubeweb/issues/1370

**Comment by elmjag** [comment]
It turned out to be pretty straight forward to move `HardwareObjectsMockup.xml `to `demo`. Just changing the default path for beamline configuration files is enough for the tests to find them:

Basically this change does the trick:
https://github.com/elmjag/mxcubeweb/commit/6c68e6600f486a011c8d30e1939178032de0bd99#diff-e9f205861e6eeb2baea071733449d0d817ad8b35c7f1f24c90ad7dc4a82139b3

The complete PR: https://github.com/mxcube/mxcubeweb/pull/1381

**Comment by elmjag** [comment]
The `test/HardwareObjectsMockup.xml` folder is now renamed to `demo`.
