### ISSUE TITLE
Error building front end when --no-optional is used

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1388]
When build front end static files, the build command fails if node packages where installed with `pnpm install --no-optional` command. I can reproduce this problem with pnpm versions 9.9.0 or 9.1.1, Node.js v20.12.2.

How to reproduce:

```
$ cd ui
$ pnpm install --no-optional
$ pnpm build
```
Build command fails with:

```
$ pnpm build

> ui@0.1.0 build /home/elmjag/mxcube/web/ui
> vite build

/home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:59
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:68:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
      at Module._load (node:internal/modules/cjs/loader:984:27)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/elmjag/mxcube/web/ui/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v20.12.2
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by axelboc** [comment]
Optional dependencies can be used for platform-specific functionality. I assume you're encountering a case where a package requires at least one of a number of platform-specific dependencies; each dependency is optional on its own, but you must install at least one of them — the one that works on your platform.

Why the need for `--no-optional` anyway? If you want to not install one specific optional dependency (because of a security vulnerability or something), then pnpm has a configuration option for this: https://pnpm.io/package_json#pnpmignoredoptionaldependencies

**Comment by fabcor-maxiv** [comment]
I was the one to add the `--no-optional` flag in our internal deployment process. I was not really understanding what this flag means (what the implications are) since I could not find any useful explanation of the "optional dependencies" concept in JS world. I assumed this flag would help us keeping things tight by avoiding installing dependencies that we don't need. So we do not need the flag, but I had nothing telling me either that we need the optional dependencies.

That's the explanation from my side. : )

**Comment by fabcor-maxiv** [comment]
It worked fine since the migration to pnpm. I do not know when it started breaking, probably with the migration to vite? Or was it a bit after the migration to vite? @elmjag do you have a guess what change made this break ?

**Comment by axelboc** [comment]
Maybe your CI workflow was executed on a runner with a slightly different set-up?

Here's an article that explains things a bit more deeply: https://www.geeksforgeeks.org/what-are-optional-dependencies-and-when-should-we-use-them/ and the official documentation of this `package.json` field by NPM, which most likely introduced this concept: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies

**Comment by fabcor-maxiv** [comment]
> the official documentation of this `package.json` field by NPM, which most likely introduced this concept: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies

This says:

> It is still your program's responsibility to handle the lack of the dependency.

and then an example showing how to write code that does not fail even if an optional dependency is missing : D

Anyway, we think it started breaking when we merged the changes for the migration to vite, and indeed:

```none
$ pnpm why rollup
Legend: production dependency, optional only, dev only

ui@0.1.0 /home/fabcor/workspace/mxcube/mxcubeweb/ui

devDependencies:
@vitejs/plugin-react-swc 3.7.0
└─┬ vite 5.4.0 peer
  └── rollup 4.20.0
vite 5.4.0
└── rollup 4.20.0
vite-plugin-eslint 1.8.1
├── rollup 2.79.1
└─┬ vite 5.4.0 peer
  └── rollup 4.20.0
```

So now, I know I can blame vite : D

I will check if I find a but report on vite's side (additionally to [the npm issue](https://github.com/npm/cli/issues/4828) mentioned in the error message).

And @elmjag I guess we can remove the `--no-optional` flag, at least for now, or we try with different versions of vite.

**Comment by elmjag** [comment]
> It worked fine since the migration to pnpm. I do not know when it started breaking, probably with the migration to vite? Or was it a bit after the migration to vite? @elmjag do you have a guess what change made this break ?

Yet, it is the migration to Vite. Starting with this commit  https://github.com/mxcube/mxcubeweb/commit/0b278703042fa6e31c2a697bfe4f42ef52ed54a9 using `--no-optional` flag does not work.

**Comment by elmjag** [comment]
Ok, I guess there is not much we can do about this from mxcubeweb side. We just need to remember to not use `--no-optional` flag, when installing front-end packages.

It still annoys me that pnpm have this magical break my build flag. *[Angry Fist-Shake](https://static.tvtropes.org/pmwiki/pub/images/oldmanyellsatcloud.png)*

**Comment by fabcor-maxiv** [comment]
"What's even the point of a `--no-optional` flag? Who would want to reduce the amount of dependencies installed anyway? The more dependencies the better! Everyone knows that. It means more features. Let's install [`everything`](https://socket.dev/blog/when-everything-becomes-too-much)!!!"

JavaScript people are funny. : D


> It still annoys me that pnpm have this magical break my build flag.

As far as I understood, it is *vite* that is to blame. As I said earlier, nothing should break when skipping the optional dependencies (or at the very least it should fail gracefully), it says so in the [documentation for `optionalDependencies`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies).

**Comment by axelboc** [comment]
Most optional dependencies won't be installed anyway — only those with compatible [`os` and `cpu`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os). The naming sucks, I agree — if it helps, just imagine that it's called `maybeDependencies` instead of `optionalDependencies`.

It's definitely not pnpm's fault, since it didn't come up with this concept, and it cannot make platform-specific decision when creating the lockfile. I also don't think it's Vite's fault, since, as mentioned, the "maybe" dependency that is compatible with the current platform is, in fact, **required**.

Like many other pnpm flags (`--prod`, `--dev`, etc.), this one is simply not meant to be used in this project. Remember, this is a front-end project; most dev and optional dependencies will never end up in the build output. They are meant to be installed in a dev or CI environment for the sole purpose of running the dev server or building the bundle.
