### ISSUE TITLE
Python test `test_set_aperture` failing

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/mxcube3#1401]
As pointed out in these:

* <https://github.com/mxcube/mxcubeweb/issues/1370#issue-2488651916>
* <https://github.com/mxcube/mxcubeweb/pull/1398#discussion_r1764471784>

it seems like `test_set_aperture` is failing... sometimes.

**Comment by fabcor-maxiv** [comment]
According to @elmjag, this might be related to a timing issue, so the test passes sometimes and the other times it fails. If I understood correctly he made an attempt at a fix in this commit <https://github.com/elmjag/mxcubeweb/commit/9e65579afdb03797a7876c2783ba34ae90dba1ac>.

**Comment by beteva** [comment]
The problem comes from the evaluation of the size of the slits. If the slits are smaller than the aperture, than the beam size is taken from the slits and the test_set_aperture fails **systematically** with 'A100' == 'slits'.  The problem is intermittent, because the test are using random aperture size, so when A100 is not used, the tests pass.
There are three solutions in order the tst to pass. Either:

1.  Remove the slits from the beam.xml
    or
2.    Set the slits bigger (or at least equal) of the biggest aperture (A100). The values are hardcoded in the SlitsMockup, so we need to change the mockup to take into account the values, set in the configuration.
    or
3.    Remove the biggest aperture from the tests.

While waiting for the SlitMockup to be changed and to make it take the values from the configuration file, I vote for 1.

**Comment by elmjag** [comment]
> The problem comes from the evaluation of the size of the slits. If the slits are smaller than the aperture, than the beam size is taken from the slits and the test_set_aperture fails **systematically** with 'A100' == 'slits'. The problem is intermittent, because the test are using random aperture size, so when A100 is not used, the tests pass. There are three solutions in order the tst to pass. Either:
> 

Oh yes, now I see it. The problem is the fact we pick new aperture randomly.

I suggest that, at least for now, we just always pick the first aperture from the available list. It works and it is still a good test on the `diffractometer/aperture` routes.

https://github.com/mxcube/mxcubeweb/pull/1402/files#diff-bb6c0006c58e00ff0c309c3cb6fa2a0b64a2aacf108701b8204e583f13f6b1d3R108

In general I think using randomness in these kind of tests is problematic. If we want to test switching to different aperture sizes, we should make a parameterized test instead. We want to keep our test suite as deterministic as possible.

**Comment by beteva** [comment]
> I suggest that, at least for now, we just always pick the first aperture from the available list. It works and it is still a good test on the `diffractometer/aperture` routes.

Very good, as the ApertureMockup is also deterministic - **A5** is the firs value ans **A10** is the one set in the init.
