### ISSUE TITLE
bring back the Draw grid V-Space and H-Space

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1443]
The` V-Space` and `H-Space` boxes in the *Draw grid* widget have been removed in this PR: https://github.com/mxcube/mxcubeweb/pull/1397

![image](https://github.com/user-attachments/assets/921c7230-2890-4f5c-98d6-7f40cb06d09f)

We are actually using these controls. We did tests doing mesh grid scans with H-Space separation last week, and it worked for us.

Can we bring them back?

As I understand, these controls are seldom used, so let's make it configurable if they are shown. I suggest to add these two UI configs:

```
show_mesh_grid_vspace   true/false
show_mesh_grid_hspace   true/false

```
With default values set to false for both of them.

As a side note, at MicroMAX currently we only want to show H-Space, but in the future we want to show both. Thus it would be nice to make each box individually configurable.

**Comment by marcus-oscarsson** [comment]
We wont have anything against re-introducing the h and v-space controls if you are using them.  They where added because we thought there might be a use for h/v space but in the end no one actually used them. Many users also found the controls strange, for some reason, and where mostly just wondering why we had those. The decision was thus to remove them and possibly replace them with something more "user friendly" when actually requested. 

It might be necessary to have a second look at these controls when we have some more feedback from the scientists but adding them back as they where would be fine.

**Comment by elmjag** [comment]
@mockoocy will work on this.
