### ISSUE TITLE
No working starting point available from fresh checkout

### ISSUE THREAD

**Issue by pkeller** [mxcube/mxcube3#180]
Following the instructions at [installation_instructions_web.rst](https://github.com/mxcube/mxcube/blob/9ce81b2c8d03fc0f2c47facbd24956c6f1e2bddf/docs/source/installation_instructions_web.rst) does not produce a working starting point, and information about how to get it to work does not seem to be available. There is a similar but different page at https://github.com/mxcube/mxcube3/wiki/How-to:-Installation. Those instructions do not work either.

Specific issues:

Navigating to http://localhost:8081 produces the following message in the server output:

> [HWR] INFO 2016-04-29 14:47:35,456 [Main] Serving main page

but the following in the browser:

> Not Found
>
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The server message comes from [Main.py](https://github.com/mxcube/mxcube3/blob/86536d601da760abac0a9ea374d3e290eca67ad1/mxcube3/routes/Main.py), where the intention seems to be to serve the file `index.html`. The only file with that name is in the [ui folder](https://github.com/mxcube/mxcube3/tree/86536d601da760abac0a9ea374d3e290eca67ad1/mxcube3/ui). It can be loaded by changing the Flask constructor call in [mxcube3/__init__.py](https://github.com/mxcube/mxcube3/blob/86536d601da760abac0a9ea374d3e290eca67ad1/mxcube3/__init__.py) to:

`app = Flask(__name__, static_url_path='', static_folder=os.path.join(os.getcwd(), 'mxcube3/ui'))`

This causes an empty page to be loaded in the browser rather than the "Not Found" message, because of the reference to the non-existent file `main.js` If the file [main.jsx](https://github.com/mxcube/mxcube3/blob/86536d601da760abac0a9ea374d3e290eca67ad1/mxcube3/ui/main.jsx) should be used instead of `main.js`, I cannot find any information about how to do this. Editing `index.html` to invoke it with the MIME type `text/babel` as described in the React docs does not work in my hands.

Finally, I tried the client-only procedure using `npm install; npm start`, but even after spending some time browsing the code I could not work out how to get past the sign-in screen.

Sorry about the narrative nature of this issue, but I wanted to put on record an overview of the difficulties involved in getting started with this, and encourage you to make the missing information available.

**Comment by meguiraun** [comment]
Hi Peter,

Thanks for the feedback and sorry for making things difficult to test. We are aware that we need to provide a better environment so that people who is interested can test mxcube3, at least with mockups. Hopefully we will have something more easy to test in the next weeks.

In the meantime, if you still are eager to try, better to have a look at the instructions in https://github.com/mxcube/mxcube3/wiki/How-to:-Installation since there are the most updated ones, but going now through the text it is clear that it is not a masterpiece of instructions.
Also, there are a couple of bugs introduced recently which will make running not easy (both are in PR, one of those created right now). So you can wait until they are accepted (tomorrow?), or use those modifications. One of those bugs was making the login fail, and the other one preventing displaying the sample view.

Apart from that, at the current state of development we need **both** backend server (the python one) and the client server (the npm one) running. We do not have a build for the client interface yet.

So, the steps are as follows:
* checkout the repo and initialize the submodules
* (if want to test today) check the pending PRs and apply those changes in your local copy
* install the python requeriments (I am with ubuntu and the pillow package was a bit tricky)
* be sure that you have the correct versions of Node 4.2.2 and npm 2.14 
* do ```npm install```
* rename ```backend_server.js.example``` to ```backend_server.js``` (so that the npm server knows where is the backend server)
* do ```npm start```
* start the redis database
* start the backend: python mxcube3-server -r test/HardwareObjectsMockup.xml/
* Go to your browser at ```localhost:8090``` (this is were the npm server is running) and the login page should appear
* since we are using mockups (in this specific list of instructions, we also run with real hardware rutinely) you can type whatever you want in the user&password (but at least one char)
* have fun

At this point you should see the "sample grid" view, where you can add samples&tasks to the queue, then go to the "DataCollection" page and you should see an image of a sample, no much to do since it is a mockup but you get the idea.

Hope it helps, and as I said before, thanks for the feedback and for trying, and sorry for making things unclear and not properly working. We will have better test environment in the near future.

mikel

![image](https://cloud.githubusercontent.com/assets/12758327/14941213/d88c421e-0f93-11e6-9461-2d036e86290c.png)
![image](https://cloud.githubusercontent.com/assets/12758327/14941223/3c7c3798-0f94-11e6-82e0-075a3155f848.png)

**Comment by mguijarr** [comment]
:+1:

**Comment by marcus-oscarsson** [comment]
:+1:

**Comment by pkeller** [comment]
Hi Mikel,

Thanks for the hints, but I still haven't got it working. Before I give more detail, I would like to be sure that my local repository is in a state that is expected to work, and there are more than two PRs that have been active over the last few days. Can you be explicit about which are the ones that you referred to? Better still, if they have been accepted already, please specify the actual commit I should check out.

As for python dependencies, I am on openSUSE LEAP 42.1 and I haven't had any serious difficulty in setting up a virtual environment with everything that is needed. My versions of node and npm seem to be correct, unless the patch version of npm is significant:

> [venv] [lonsdale]mxcube3/try2/mxcube3-348 > npm --version
2.14.7
[venv] [lonsdale]mxcube3/try2/mxcube3-349 > node --version
v4.2.2

Regards,
Peter.

**Comment by mguijarr** [comment]
We would need more details in order to understand what exactly doesn't work at your place. Otherwise I would suggest you to wait at least until next MXCuBE meeting, before trying MXCuBE 3 again. Indeed, there will be major changes and the project state is currently under active development, which means we won't deliver anything stable before the first milestone (for MAX IV inauguration).

**Comment by pkeller** [comment]
I understand that, but referring to two recent PRs, when twelve have been opened in the last 4 days just leaves me guessing. Can someone please confirm the ids of the PRs that Mikel referred to?

**Comment by meguiraun** [comment]
Hi Peter, I was refering to https://github.com/mxcube/mxcube3/pull/181 and https://github.com/mxcube/mxcube3/pull/182, which are already merged.

**Comment by pkeller** [comment]
Hi Mikel, thanks, that is very helpful. This is how far I have got:

I had set up the python dependencies from a previous checkout with:
```
pip install numpy
pip install -r requirements.txt
```
(numpy was installed explicitly to avoid dependency failures with scipy)

Checked out with `git clone git@github.com:mxcube/mxcube3.git --recursive` which gave:
```
[venv] [lonsdale]mxcube3/try3/mxcube3-369 > git log -n 1 | cat
commit f9bb51fe27700d47daac455eecdbbc07399153a4
Merge: ff8e0a8 edda64c
Author: Matias Guijarro <matias.guijarro@free.fr>
Date:   Mon May 2 12:45:14 2016 +0200

    Merge pull request #183 from bolmsten/mxcube-fabric
    
    Colors for running samples and a refactor of SampleView
[venv] [lonsdale]mxcube3/try3/mxcube3-370 > git submodule status
 b87af4d225b45779ece73d9987f4bafb52ed3cd5 mxcube3/HardwareObjects (remotes/origin/2.2)
 c307ad870056775a6c76506700f6d18bb67a860b mxcube3/HardwareRepository (remotes/origin/serialization)
```

Check npm/node versions:
```
[venv] [lonsdale]mxcube3/try3/mxcube3-376 > npm --version
2.14.7
[venv] [lonsdale]mxcube3/try3/mxcube3-378 > node --version
v4.2.2
```
Then `npm install` and `mv backend_server.js.example backend_server.js`

Finally, started the server processes with:
```
/usr/sbin/redis-server
npm start
python mxcube3-server -r test/HardwareObjectsMockup.xml/
```

Going to http://localhost/8090/ got me to the login screen, but when I tried to log in I got "Failed Sign In" and the MXCuBE server gave me the following stack trace:

```
* [HWR] INFO 2016-05-03 14:41:37,004 aaa
Traceback (most recent call last):
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/sync/pkeller/mxcube3/try3/mxcube3/mxcube3/routes/Login.py", line 52, in login
    mxcube.queue = jsonpickle.decode(session.get("queueList", "{}"))
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/jsonpickle/__init__.py", line 152, in decode
    return unpickler.decode(string, backend=backend, keys=keys)
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/jsonpickle/unpickler.py", line 26, in decode
    return context.restore(backend.decode(string), reset=reset)
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/jsonpickle/backend.py", line 193, in decode
    return self.backend_decode(name, string)
  File "/mnt/sync/pkeller/mxcube3/venv/lib/python2.7/site-packages/jsonpickle/backend.py", line 205, in backend_decode
    return self._decoders[name](string, *optargs, **decoder_kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

"aaa" was what I entered for the LoginID.

I'll keep looking to see what I can find, but if anyone can give me any hints it would be very helpful.

**Comment by mguijarr** [comment]
Could you please tell us the return value of `session.get("queueList", "{}")` in `/mnt/sync/pkeller/mxcube3/try3/mxcube3/mxcube3/routes/Login.py` ? Seems like the `session.get` is not returning a string.
Maybe there is some garbage in your redis database, you can start `redis-cli` and do `FLUSHDB`.

**Comment by meguiraun** [comment]
could you try to clone the repo as this: (I know the wiki says other thing)
```
git clone git@github.com:mxcube/mxcube3.git
git submodule init
git submodule update
```

**Comment by mguijarr** [comment]
@meguiraun : I don't think Peter has a cloning problem, he used `--recursive` which is the equivalent of `submodule init` then `update`

**Comment by meguiraun** [comment]
@mguijarr : ok, I am just your git padawan :-) 

Then an ugly solution could also be to comment the problematic line:
```
File "/mnt/sync/pkeller/mxcube3/try3/mxcube3/mxcube3/routes/Login.py", line 52, in login
# mxcube.queue = jsonpickle.decode(session.get("queueList", "{}"))
```
I have tested now, and If redis is empty that line will not work at all, need to figure out why though...

**Comment by pkeller** [comment]
Hi, trying Matias' suggestion first, `session.get("queueList", "{}")` gives me an empty dictionary, `{}`.
I also tried flushing the redis database as suggested. Also, to be extra sure, I stopped the redis server, deleted dump.rdb and started redis-server again. Same result.

**Comment by pkeller** [comment]
@meguiraun @mguijarr Commenting out that line in Login.py works for me too: I get a very basic start screen. It is a long way short of the example that Mikel showed, but I think that it is good enough for the moment, since I can interact with it (e.g. add a sample by hand). At this stage, I just wanted something that lets me explore the underlying technology.

Thanks!

**Comment by meguiraun** [comment]
great! That line will give the user to restore a saved queue, but it looks like it need some debugging...

thanks,

**Comment by pkeller** [comment]
I guess that I don't see any sample changer contents because I am not connecting to an ISPyB instance? That's OK as well: my interest at the moment is with what happens after a sample is mounted.

Thanks again,
Peter.

**Comment by meguiraun** [comment]
You can "check sample changer contents" and you will get some dummy samples to work with. Also, in the Datacollection view you could try a centring (weeell... static image, only one click required...) and play with the right click button.
