### ISSUE TITLE
Sample Grid Prototype

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#242]
Hi all,

We thought it would be good share the latest development of the Sample Grid, so that you guys can follow whats happening and even try it out. There is still plenty of work to be done overall, from design to functionality. So be prepared that its in a early stage :). The branch is called samplegrid-prototype.

Its currently possible to move sample items around in the grid by selecting it and pressing the little cross in the upper left corner. (Its currently not possible to move several items at once). It's further possible to multiple select and pick items for collection.

The design have changed slightly from what we purposed when you were here last time. The Pipeline mode and collect button have been moved above the sample grid itself. All the controls above the sample grid is also contained in a "sticky" container so that they scroll with the screen when there are alot of samples.

All of these things are of course under development and evaluation so they might change during the process. We are really grateful  for any input on anything from design to code details, although keep in mind that its in a quite early stage :). We also understand it might not be the best time for you guys to check this thing out right now.

I'm going to spend the next couple of days to do some refactoring and pay pack some of the "messy code" debt that we have :). We would like to continue with the work on the queue after that, hopefully at the end of this week or beginning of the next. It would be great to know were you are on the topics we discussed when you were here last time, since this impacts the queue behavior ?

Enjoy,
Marcus

**Comment by amilan** [comment]
Hi Marcus, 
Thanks for sharing this development. We understand that is not the final version and it's still under heavy development, so no problem with that, is always good to have it available in order to provide you better feedback.
We have scheduled a review here at Max IV for tomorrow (Friday) morning, so we will inform you soon.

Feedback is coming ... 

Thanks,
Antonio.

**Comment by marcus-oscarsson** [comment]
Hey Antonio,

That's great to hear, happy to know that its useful for you. We are in particular interested in your thoughts about the queue and the concept in general, at least this stage at least :).

Ciao !
Marcus

**Comment by mguijarr** [comment]
In order to make it easier to understand this proposal, I can clarify some terms a bit:

* Selecting a sample *= clicking on the sample card, or dragging the mouse over multiple cards*
  * to **add a task** on the sample
    * e.g characterisation (**pipeline**)
  * to **move** the sample
    * using arrow keys or the buttons that appear on the sample card
  * to **pick the sample** for data collection
    
When a sample is selected, a thick dark border is drawn around the sample card.

* Picking a sample *= clicking on the checkbox of sample card, or using the __Pick__ buttons*
  * to **add to the queue**
  
When a sample is picked, the card background becomes light blue.

**Comment by mguijarr** [comment]
Discussion will continue but issue can be closed for now.
