### ISSUE TITLE
Cant add sample in "Manual Mount"

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#249]
Hello,

It seems like set phase somehow is unavailable in the mockup version, this makes it impossible to add a sample manually since the Add Sample button is disabled.

This is not very urgent and I can Imagine to fix it myself if no one else takes it, just adding it for the record since I'm currently doing some other things not directly related to this feature.

Antonio, I assign it to you so you can either assign it to one of you guys or just unassign yourself and Ill take it.

Cheers,
Marcus

**Comment by mguijarr** [comment]
`set_phase` is present in `DiffractometerMockup.py` as far as I see, so the problem is not this. That said, the `Add sample` button is disabled (at least for us), does someone know why ?

**Comment by meguiraun** [comment]
you can only add a sample if you are in transfer mode, but it is not working in mockups… I see it now…

**Comment by mguijarr** [comment]
Thanks for looking at this Frederik :+1: 

By the way, this is highly specific to MD2/3 ; I understand that it is better if the diffractometer is in transfer mode (beamstop down, light down, etc.) when putting a sample manually, but I thought the operation in MXCuBE 3 was more a logical step (like, "I add a sample, that has been mounted manually, regardless of how it has been mounted") than something involving real hardware.

Otherwise there should be a "Set to Transfer mode" button, no ?

Personally I would not look at the state of the diffractometer when adding a manually mounted sample.

**Comment by meguiraun** [comment]
hi, no problem... I know that I look like a swedish hehehe!

I think that is better if we ensure that the md2/3 is in the appropriate mode before a user's hand get close to it. What do you mean by the "Set to Transfer mode" button? As it is now, whenever you press the add button it also sets the md to transfer mode.
Anyway, we can discuss this face to face.
