### ISSUE TITLE
npm installation issues

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#270]
on kubuntu 16.04 the ```npm install``` fails with the following:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spawn-sync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mxcube/Documents/mxcube3/npm-debug.log
mxcube@mxcube-VirtualBox:~/Documents/mxcube3$ vim npm-debug.log
```

Since the post-install script is not executed fabric library is not installed, which causes the client not to load. Installing manually fabric seems to solve the issue (```npm install fabric```)

I am using the default versions of ubuntu: npm 3.5.2 and node 4.2.6. 

Why is fabric installed in the post-install stage?

**Comment by mguijarr** [comment]
See PR #185, but in short here is why: we should always use npm instead of adding our own files,
at some point it was difficult for fabric because this package wanted to compile a lot of stuff (Cairo and
other libraries) for server-side rendering, which we do not use. When the fabric team moved those dependencies to optional dependencies, it became possible for us to use npm to install fabric as long as the '--no-optional' flag is passed - having this flag in post install is the only way I found.

The question should be: why `spawn-sync` is failing ? What is it, by the way ?

**Comment by mguijarr** [comment]
Any news on that?

**Comment by mguijarr** [comment]
@meguiraun do you have more news on that ?

**Comment by meguiraun** [comment]
No news on this... but it looks something specific to the default versions of ubuntu npm. I have just do a clone and a fresh install without problems.

Should we close this?
