### ISSUE TITLE
couple queue_entry with QueueModel

### ISSUE THREAD

**Issue by JieNanMAXIV** [mxcube/mxcube3#329]
The original question was that we noticed that DataCollectionQueueEntry was not created when a collection plan was returned by EDNA_char in the [CharacterisationQueueEntry](https://github.com/mxcube/HardwareObjects/blob/2.2/queue_entry.py#L1028). 

In the Qt Brick, a queue_entry is added automatically when a new queue model is added by
[TreeBrick.add_to_view](https://github.com/mxcube/mxcube/blob/7db54a725aa043ed97d619ffcb513e277cb8dcb2/Bricks/Qt4_TreeBrick.py#L254), which finally calls view_created() in [queue_model](https://github.com/mxcube/HardwareObjects/blob/2.2/QueueModel.py#L232). 

In the current mxcube3, QueueEntry is created by [qutils.py](https://github.com/mxcube/mxcube3/blob/4ec1c6a99bf4ebcc73e73e5955e59d4093cc1745/mxcube3/routes/qutils.py#L466) and there is no connection between QueueModel and queue_entry. This needs to be refactored with a mock view in the back end server.

**Comment by marcus-oscarsson** [comment]
So this is the mail I sent to you earlier today, pasting it here for completeness:

Hello,

So I looked at the code for characterisations, I imagine that what you refereed to was the
method add_to_view in dc_tree_widget.py (line 375) ?

The code is maybe not very elegant but what it does is to listen to additions in the model,
these changes are emitted as the signal child_added (add_child on the QueueModel). The method
creates a corresponding view and calls the method view_created on the QueueModel. The idea
is that the UI creates the necessary view and couples it with an entry. Again, this is maybe
not the best way of doing it and having the view so tightly coupled with the an entry is in
retrospect not a good thing.

Luckily its not a big problem the only thing we have to do is to create our own add_to_view
handler, maybe with a more suitable name. Like just queue_add_child_cb or whatever you think
is good. We need to create our QueueEntry and view in this method, the view would just be
to emit ADD_TASK to the UI. Basically like it is in MXCuBE today but instead of creating a
qt widget we create a Mock view and send ADD_TASK to the UI.

We might need to take another look at the queue at a later stage and decouple some of these
things. This was in fact something I wanted to do already before I left the project last time,
although I did not have enough time. So I already looked through these things, and I don't
believe it will be such a big undertaking as it might seem. However I think we should wait
with that until we a well working web application.

I hope I was able to clarify/help you guys. Please let me know if you have more questions
about the queue or other things. I'm also happy to discuss these things on Skype if you need
to know more details.

Cheers,
Marcus

**Comment by marcus-oscarsson** [comment]
I consider that we know what to do from here, so I'm closing this issue now.

**Comment by marcus-oscarsson** [comment]
I might have miss understood the issue, it was maybe for Mikel. So ill reopen it and put him as an assignee, and then he can close it if it was not the case :)

Sorry

**Comment by meguiraun** [comment]
(Replying here to the email)

I think before start changing the queue/qutils again (I really like your refactoring Marcus!) we can try to a specific solution to this problem. So at first, add a method in routes.qutils which listens to the ‘child_added’ signal for adding the missing entry, with some logic to check who has added the child (the characterisation or a client). I already started typing this solution without knowing anything about the view_created method …

Refactoring of the queue model and/or proper usage of the view_created would require more work. Be lean my friend…

We will do a PR from the WIP characterisation soon.

**Comment by marcus-oscarsson** [comment]
Okey, sounds excellent

**Comment by mguijarr** [comment]
I am trying to clean issues today... What are the news on this one ?

**Comment by meguiraun** [comment]
related to #331, we can close this.
