### ISSUE TITLE
Using a module bundler, ES6 and other philosophical questions about front-end development

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#34]
I studied a lot the way front-end developers are working in general with newest tools that exist in the Javascript and web development world, and lately lines have moved a lot to improve code organization, automatic processes (including testing) and even code writing itself so I wanted to share my findings with you guys, so we can decide which direction to go. Of course I have an opinion :) But before doing any pull request I prefer to explain first.

MXCuBE 3 client-side code is depending on React, Bootstrap, and many other little libraries. There is going to be more and more dependencies as features grow, which is normal. On the server dependencies are handled in requirements.txt and distutils in general, that's great - I always wanted to have a similar mechanism for Javascript code. I realized it exists, in different forms... It turns out people are setting up tool chains to handle dependencies (and much more), mixing tools like bower, grunt, gulp, yeoman, browserify, webpack...

Whatever the tool chain is, the idea is always the same:
- to make it easy to download Javascript libraries (possibly with CSS and images) and have them integrated in the project
- to maintain a registry of library versions 
- to do some processing on the code (syntax checking, transpiling, minifying, etc.) in order to produce a final .js file
- the final .js file is highly optimized, "production-ready" and contains all dependencies inline

In order to do all this, my personal choice is [webpack](https://webpack.github.io/) since it does the job of browserify + gulp (or grunt), using "standard" tools (like Node and npm) for package download and versions management.

So in my MXCuBE 3 repository I configured webpack and node modules to work with our code base.

There is more... I think we should write our Javascript code in ES6 syntax ; this is the syntax for the upcoming versions of Javascript, it is a standard that just needs to be implemented in all browsers.
It makes code much more readable, in particular when working with React components if we decide to follow the principle of having "1 .jsx file === 1 component" since it becomes possible to use ES6 modules syntax to import code from other modules just like we do in... Python. Thanks to the webpack installation it is the same for third-party dependencies too :) So one can write "import React" or "import { Button } from Bootstrap" for example.

[Babel](https://babeljs.io/) is a tool that converts ES6 code to ES5, to make it runnable on all web browsers. I added it to the webpack configuration, so it becomes transparent : we can write ES6 code and the final .js file is in ES5.

I followed guides on the net and I also configured [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) : it allows to test the UI without starting the "real" MXCuBE 3 server. So the front-end developer can focus on the user interface, not worrying about real hardware or whatever. A very interesting feature of webpack is hot reloading ; it allows code changes to be immediately visible in the web browser during development.

I would like to get your opinion on all this, as soon as possible in order to see if we can merge a
PR from my repository and to continue development on good rails, or if you disagree we can
see how to organize all this differently.

**Let's try it !**

You can clone [my repository](http://github.com/mguijarr/mxcube3) *be careful to use branch webpack*:

    git clone git://github.com/mguijarr/mxcube3 -b webpack

**How to use webpack ?**
- first install Node and npm, required version is 0.12 at least ; for Debian-based systems I recommend doing this:

    ````
    # Note the new setup script name for Node.js v0.12
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

    # Then install with:
    sudo apt-get install -y nodejs
    ````
- then just install MXCuBE 3 dependencies:

    ````
    cd mxcube3-repo
    npm install
    ````

- finally, run webpack in development mode:

    ````
    npm start
    ````

Open a web browser to [http://localhost:8090](http://localhost:8090) and see what I am working on...

**What do you think ?**

**Comment by meguiraun** [comment]
hi,
I tried also a little bit this kind of project organization... lucky me you have gone further than me! I like the approach, and I also think is necessary for the deployment. I will have a look at you code right now!

**Comment by mguijarr** [comment]
Great! Let me know if there is anything unclear and of course don't hesitate to ask questions or to share some feedback.

**Comment by IvarsKarpics** [comment]
Hi,
I tried with virtual machine on almost clean ubuntu. By following your guidelines it worked like a charm.
I am not so familiar with webpack, but it looks like it does all the dirty work and launching app is just a oneliner. This looks very easy and smooth. 
Thanks Matias!

**Comment by meguiraun** [comment]
Hi,

I also tried and feel very easy to set up, very comfortable for the development (automatic recompile etc..) and mandatory for the deployment/production. I really like the simplification of the html file, it is almost empty, and the transparent usage of external libraries.

A few questions:

* For any development on the web-interface one only needs to change/add code in main.jsx? Any import present in main.jsx (or SampleGrid.jsx, or whatever file) will be automatically handled by webpack? (I am thinking on how to add new jsx components)

* Regarding the ES6 syntax, what happens if we mix ES6 and ES5 in the project? I do not see any problem using ES6… but perhaps we will need to add a wiki page about it...

* Webpack server, is it only intended to test the ui? Or, is it possible to allow http put/post request? That is also part of the interface, it would be nice to see the request that goes to the server. Perhaps, for that we might need to launch the full mxcube server.

I think this is the way to go for the development, and I would accept immediately the PR (If I were integrator... )… however our new web-developer will start working with us in a couple of weeks (the decision was taken earlier this week) so I would suggest to wait until he is with us. I really like your proposed approach but I think is a bit unfair for our new colleague to accept this PR days before he starts working specifically on this stuff.

In any case, we need to do a planning meeting! I will talk to our people and we will propose some date.

By the way I have been working on the sample view/centring, and now I can do the sample centring through the web interface (both lucid and 3-click). I will update the issues with this info. I have not done the PR before because I am chasing a bug which causes big network usage… 

cheers and thanks for this!

mikel

**Comment by mguijarr** [comment]
Hi Ivars and Mikel,

First of all I would like to share the good news: my daughter is back from hospital since yesterday,
yeepee :) So I am writing from home, I took some days off but I am happy to participate in this
discussion !

So regarding your questions:
- indeed, all imports are handled by webpack ; the resolve path for modules is in the `webpack.config.js` file - in my repository I set the path to `./mxcube3/ui`, and if it cannot be find over there, `./node_modules` is searched
- about ES6 syntax: you can freely mix ES5 and ES6 (even ES7...)
- I think the webpack server is only for testing the UI - of course you can make AJAX requests
from the Javascript code, but nothing would reply by default... An idea would be to implement test replies, so we can fully test the UI without the need for the Python server and it would be useful as a kind of API validator. However I don't know how to do it at the moment. I would like to have add automatic testing to the tool chain.

I need to do more coding in order to understand how to best handle React components and HTML
structure - as you said, I would be happy if the HTML file is kept at the minimum, almost empty, and
all the logic should go in `main.jsx`, where components would all be built... 

Regarding the new front-end developer : I think we cannot really afford waiting. In my opinion we should move to a proper front-end workflow as soon as possible and eventually the new developer will propose changes based on his experience and knowledge. I don't see why it is unfair - there are many (many) more tasks to do, so if we already sort the basics out first, I see it only as a productivity boost.

I can tell you another good news: ESRF directors approved a 3-year old position for MXCuBE
and ISPyB development :) We will start hiring process soon.

Indeed we should have the planning meeting asap ; next week ? Any day is ok for me.

It's great you're making good progress on the sample centring UI - did you commit changes in your own github repository ? I may give you some help maybe if you're stuck with a bug.

Cheers,
Matias.

**Comment by meguiraun** [comment]
Glad to read that news! That must be a big relief for you!

Thanks for the answers, and good to read that someone else will also join your team! 

Perhaps we can discuss about this changes in the meeting (we will try to send you a tentative/proposal date soon, we are having a busy week...).

Regarding my bug... I have push everything to my fork, I removed all the sse stuff hoping that the problem was related to that but not... The problem is that this line [SampleCentring]  (https://github.com/meguiraun/mxcube3/blob/master/mxcube3/routes/SampleCentring.py#L33) does not wait (I tried with both L33 and L34), it executes inmediately probably because I already have a value (so I am not clearing the data perhaps?)... 

The origin of the event comes from the camera_hwobj, where I did set a ```time.sleep```, in fact a sleep there makes sense to me. Looking at timing at this HO I do not see anything wrong.

I think I was having this problem from the beginning but I have not noticed until now when I was trying to connecto to our beamline though a limited vpn access ... I was sending the image at a very high rate, but I did not notice anything when I was inside the beamline network.  In the process of debugging I moved to only use mockups, so it is nothing related to real hardware or network (now I run the server in a vm and I use the browser of the host machine)

I (kind of ) fixed defining a ```time.sleep``` [here] (https://github.com/meguiraun/mxcube3/blob/master/mxcube3/routes/SampleCentring.py#L38), but it does not look very elegant to me...

I started with the wiki to talk about the [centring] (https://github.com/mxcube/mxcube3/wiki/Sample-Centring), it is mostly for my understanding but I will try to make a real video with all of currently working features of the sample video/centring and publish somewhere so you can see.

cheers,

mikel

**Comment by meguiraun** [comment]
Solved the no-wait issue. Instead of using ```gevent.event.AsyncResult``` I switched to ```gevent.event.Event()```!!!

I only need to add a global for storing the data ( ```AsynResult``` can hold data)

**Comment by mguijarr** [comment]
Added wiki page with [more information](https://github.com/mxcube/mxcube3/wiki/Webpack-and-frontend-development-stack)
Will now wait for Mikel to make his PR first, then I will make the PR with all changes explained in the wiki page, then we can close this issue.
