### ISSUE TITLE
Beam center is displayed at the wrong place

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#360]
At least on firefox, the beam is displayed with a small offset in sample video, it is shifted a bit to down-left direction. The beam position taken from hardware object is right, so the bug must be with some error with the coordinates when resizing video image.

**Comment by bolmsten** [comment]
When I call sampleview/camera I get: 

  "imageHeight": 493, 
  "imageWidth": 659, 

and then when I call:

  "position": [
    300, 
    300
  ], 


Would this not match the position that we see?

**Comment by mguijarr** [comment]
Ah ah. Er... Indeed. Sorry for the noise.

In fact we got confused by switching too frequently from testing environment (with `BeamInfoMockup`, where beam center is set at (300,300) like you found), and our real hardware environment with the beam
position at the right place. And so I switched the two in my head, thinking that the beam centre was wrong with the right hardware object... My bad.

So this issue is almost closed ;)

Indeed, there is a little thing that remains: there are 2 objects, the red cross and the blue circle. The red cross should always be at the centre, whereas the blue circle represents the beam and it should be at the beam position. At least it is like this in MXCuBE 2, and without more information from scientists I think it
should stay like this in MXCuBE 3.

**Comment by marcus-oscarsson** [comment]
Is someone working on this for the moment, and do we agree on that behavior ?

**Comment by bolmsten** [comment]
@JieNanMAXIV  do you agree with the behaviour Matias is describing? In that case I will finish this up.

**Comment by JieNanMAXIV** [comment]
I have discussed this with Marjolein. Below is what we think,
For experiments, users care more about the center of the beam, which can be useful for crystal centering esp. with large beam or small beam with high zoom etc. The center of the image is not very informative for users and would not help much with their experiments (Let me know if we miss some scenarios). At the beamline (at least for us) we try to optimize the beam to or close to the image center because the photo-diode is well aligned with the on-axis camera, but this is not necessarily always true and also if one use other methods to align the beam.

@mguijarr, could you please ask the scientists at your site for their opinions? If it works differently at ESRF or other places, perhaps we can rename the center to something more generic or simply cross.  The client takes the values from whatever the diff hwobj provides, which can be either image_center or beam_center, depending on site implementation. 

I think we can close it if you agree :)

**Comment by ddesanctis** [comment]
I think there is a conceptual (but in the end lost) difference, with the cross not being the center of the image, but rather the center of rotation. In our case these have always been coincident because of the way the experimental setup is designed (everything on the experimental table, which is aligned to put the beam in the center of the image and with the center of rotation). While I can think of situation in which the center of rotation is decoupled from the center of the beam (top hat beam defined by slits, making a sort of precession) I'm not sure this is relevant, so I think the two object can be merged. On the GUI I still think that the cross is a good think to keep, it helps to visually check that the rotation axis is well aligned, and facilitate users centering

**Comment by JieNanMAXIV** [comment]
Agree that we should keep the cross and also it's useful to show the rotation axis. But I am not sure what do you mean by the rotation center, is it where the beam and rotation axis cross? 

The rotation axis should be represented by a line being an axis. For the situation you described and to be able to check if if the rotation axis is well aligned with the beam center, it's important to show the beam center, that's why we proposed that the red cross should be the beam center instead of image center. 

Just to clarify, the cross here refers to the small red cross on the sample video, not the large yellow cross during centering.
