### ISSUE TITLE
Task final state is not updated in Sample View page (queue)

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#387]
Once a task is executed, it turns "blue" ; however, the final state is not properly reported in the queue. It should be "green" if successful, or "red" (light red) if an error occurred.

With PR #385, the internal state on the server seems to be updated, because reloading the client shows executed tasks as "green". However, it is always green (even if the task could not be performed, or had an error).
With current master, the task state does not seem to be reported at all ; I guess it is missing a signal somehow.

**Comment by meguiraun** [comment]
The failure with the last signal could be due to a crash in the `signals.collect_oscillation_finished/failed` methods, I saw if crashing if `mxcube.rest_lims.get_dc` does not exists. thus not reporting the final state.

I will check the state when reloading (#385), it should not be always green...

**Comment by mguijarr** [comment]
Thanks Mikel.

I also saw this `.get_dc` problem - let's see if I can find where it comes from...

**Comment by meguiraun** [comment]
I think we started using the rest_lims recently, mockups xml files not updated?

**Comment by marcus-oscarsson** [comment]
Hey !

Yeah, that's probably my bad ! Because there is no proper mockup for the ISPyBRestClient so we are using the ISPyB2ClientMockup by default. We added the method get_dc fairly recently so it have been working fine until now. It will of course still work fine if we are using the "real" hardware objects configured properly.

I will take the time to make a ISPyBRestClientMockup to handle this !

Ciao !

**Comment by mguijarr** [comment]
More news on this : I tried yesterday on a beamline, with the right ISPyBRestClient - the problem is still there. So it doesn't come from `.get_dc`.

**Comment by mguijarr** [comment]
Fixed in #437
