### ISSUE TITLE
Forbid removal of past data collections

### ISSUE THREAD

**Issue by mguijarr** [mxcube/mxcube3#392]
Already collected tasks are part of history, and cannot be changed or removed.

**Comment by mguijarr** [comment]
We also said:
- [ ] remove Change button, a click on Parameters link will show the parameters instead
- [ ] ensure past data collections cannot be changed
- [ ] Delete button to be moved as a cross at the top right corner
- [ ] link to Results as a text label instead of a button (more compact)

**Comment by marcus-oscarsson** [comment]
Hey, 

So I did something for the delete buttons, Ill leave the redesign to you guys. Or just let me know if you would like me to do it ...

Marcus

**Comment by amilan** [comment]
Hi, 
I'm cleaning the board and this issue appears as done, shall we close the issue? or is there anything missing?

**Comment by marcus-oscarsson** [comment]
Hey !

I only did a part of it since some other parts involved some redesign of the queue UI. We discussed this during the meeting and It seemed to me that it was more Fredrik or Mikel that were going to take care of the queue UI part. So remaining to-do is:

- [ ] remove Change button, a click on Parameters link will show the parameters instead
- [ ] Delete button to be moved as a cross at the top right corner
- [ ] link to Results as a text label instead of a button (more compact)

But I might of course have misunderstood, just let me know if you think I should take of it

Marcus

**Comment by meguiraun** [comment]
hej, you are right, it is on our desk.

**Comment by meguiraun** [comment]
see https://github.com/mxcube/mxcube3/pull/462

**Comment by marcus-oscarsson** [comment]
So I consider this done, right Mikel ? If not please re open it
