### ISSUE TITLE
Prevent wrong parameters to be applied

### ISSUE THREAD

**Issue by amilan** [mxcube/mxcube3#398]
**User story**
As a user, I don't want to be able to apply wrong parameters for beamline specifics, so that will be a cause of problems.

**Acceptance criteria**
Given a configuration file with parameters, 
When I write wrong values, 
Then the interface will not allow me to write them and will notify me.

**Comment by beteva** [comment]
Please consider in the acceptance criteria that the parameters might be in the hardware configuration (e.g. motor limits) and not only in the configuration file.

**Comment by meguiraun** [comment]
Closing this one since #422 was accepted and merged. See the PR discussion for more details, as a summary:
* if any parameter in forms {datacollection, char, helical} is wrong, the problematic input field is set as warning and the "run now" and "add to queue" buttons are disabled until the user types a correct value
* limits come from hwobjs (moveables and parameters)
