### ISSUE TITLE
Investigate scan plots tools

### ISSUE THREAD

**Issue by amilan** [mxcube/mxcube3#401]
We need to investigate scan plots solutions.

**Comment by mguijarr** [comment]
I recommend to base the plots in MXCuBE 3 on [dygraphs](http://dygraphs.com/), it is a very efficient chart library for real time data display compared to other solutions like [plot.ly](https://plot.ly/) or [chartjs](http://www.chartjs.org/) and it is also much more lightweight.

There is no official react support -no graph/chart/plot library has, since it is more canvas rather than DOM- but a guy did a component: [react-dygraphs](https://github.com/motiz88/react-dygraphs). It is available via npm.
