### ISSUE TITLE
Login, Longing-out and then logging-in again does not work

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/mxcube3#663]
Longing-out and then logging-in again does not work, cant login

**Comment by meguiraun** [comment]
Looking at this.

I cannot reproduce:
* when login as username (our case) and real Ispyb hwobj.
* when login as proposal and mockups

Using ispyb mockups and user login, it happens due to inconsistent dict between the dummy `__test_proposal` and the session obtained after calling `get_todays_session`. Probably something similar is happening with real hwobj and proposal login, how do you see this issue?

I will try to improve those dict structures, they have been giving problems in the past as well...

(testing with #653 and corresponding pr in HR, it may alleviate a bit the problem, but it definitively does not solve)

**Comment by marcus-oscarsson** [comment]
I have an issue when for instance doing this: sign out -> sign in -> goto sample grid -> go to datacollection (fails)

 - It seems like current sample is not properly cleared on the server

Whats otherwise the status of this ?

**Comment by meguiraun** [comment]
is this solved now with the last PR? (I think so)
