### ISSUE TITLE
Queue operation

### ISSUE THREAD

**Issue by meguiraun** [mxcube/mxcube3#73]
Hi,

I have created a wiki page explaining the queue hardware object (or trying to...) [here] (https://github.com/mxcube/mxcube3/wiki/How-to:-Queue-(backend)). Could you have a look at it and check if have not ruined the queue model operation? It works for me but I am not sure if this is the intended way of working with the queue.

I will continue with the queue backend based on what it is in that wiki page, and of course, I will continue updating the wiki (how to configure a datacollection for example...)

thanks,

**Comment by IvarsKarpics** [comment]
Great work, thanks! 
My suggestion would be to add more information to README file. In case of mxcube3 add README file, because thats the first info what a developer sees.

It could be in a style:

MXCuBE
-----------
Information about collaboration

- Project webpage

Short info about qt/web gui.

MXCuBE Qt version
-------------------------
- Overall information
- How to install and run Qt version
- User manual

MXCuBE Web version
---------------------------
- Overall information
- How to install and run Web version

And in mxcube3 README file could have overall information and last paragraph.

**Comment by meguiraun** [comment]
yes, the Readme is still missing. I will create (and fill) the Readme file for mxcube3
