### ISSUE TITLE
energy limits == current energy -> interface freeze during validate

### ISSUE THREAD

**Issue by sallazda** [mxcube/mxcube3#775]
If one or both limits of the energy motor is equal to the current energy, the interface freeze when you add the current point to datacollection.

**Comment by marcus-oscarsson** [comment]
Hi Yoann,

I see, thanks for reporting this, its not something we have seen here so far. I will try to reproduce it here,
I suspect that it is the interpolation that is done to get a valid resolution range that goes "crazy" if the current energy is at the limit value.

Try to disable [this (https://github.com/mxcube/mxcube3/blob/e7a2cb3fae7cbf7970bc40a2c56e16163818e246/mxcube3/ui/components/Tasks/validate.js#L21 ) code ans see if it makes a difference ?

We can then make a fix for the limit case if it turns out that is the problem

Marcus

**Comment by sallazda** [comment]
I update to master version and the issue was corrected.

`  if (energies.length > 2) {
    resMin = everpolate.linear(currEnergy, energies, limitsMin);
    resMax = everpolate.linear(currEnergy, energies, limitsMax);
  } else {
    resMin = props.attributes.resolution.limits[0];
    resMax = props.attributes.resolution.limits[1];
  }
`

**Comment by marcus-oscarsson** [comment]
Ahh, great ! :)
